all:
	./compile_bootstrap_nl.sh

strict:
	./compile_bootstrap_nl.sh -D _STRICT

debug:
	./compile_bootstrap_nl.sh -D _DEBUG -D _STRICT
#	./compile_bootstrap_nl.sh -D _DEBUG

clean:
	rm bootstrap-nl *.o

